name: minesweeper
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <3.68.1'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  dart_code_metrics: ^5.3.0
  lints: ^2.0.0
  test: ^1.16.0
